### ISSUE TITLE
No files/directories in pip-egg-info (from PKG-INFO)

### ISSUE THREAD

**Issue by derPuntigamer** [prody/ProDy#659]
The current pip (/pipenv) install in prody fails, making prody unsuitable for installation as a dependency. Installing prody globally/manually can lead to version problems. Please look into the matter or tell me, how I could fix this.

```
$ pipenv install prody                                  
Installing prody…
Collecting prody
  Downloading https://files.pythonhosted.org/packages/40/52/f16877492ea065cd26105830be12c72b06860ac5fc32ce7929d012588783/ProDy-1.10.2.tar.gz (1.5MB)

Error:  An error occurred while installing prody!
No files/directories in /tmp/pip-install-ab65ohcm/prody/pip-egg-info (from PKG-INFO)
```

**Comment by SHZ66** [comment]
May I ask which platform this is and which version of Python you are using. I just tried it on a Linux machine (Ubuntu 14.04 with Python 2.7.15 and Python 3.6.5) and it both succeeded. 

If you are using Windows, please download the installer from [PyPI](https://pypi.org/project/ProDy/#files).

**Comment by derPuntigamer** [comment]
Please be aware that the command `sudo pip install -U prody` **works if ProDy was installed manually** beforehand. I guess the installation process creates the necessary egg info for future updates or ProDy will be upgraded independently from its dependencies, which could be unfortunate. Test the pip install process in a clean environtment.

I have tested it with Python 3.6.5 in 3 scenarios:

1. Outside of pipenv, normal user:
```
~/Source/pipenv_test 
➜ pip install -U ProDy
Collecting ProDy
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/40/52/f16877492ea065cd26105830be12c72b06860ac5fc32ce7929d012588783/ProDy-1.10.2.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 406kB/s 
No files/directories in /tmp/pip-build-2ASyM8/ProDy/pip-egg-info (from PKG-INFO)
```

2. Outside of pipenv, with sudo:
```
~/Source/pipenv_test took 3s 
➜ sudo pip install -U ProDy
The directory '/home/daniel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/daniel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting ProDy
  Downloading https://files.pythonhosted.org/packages/40/52/f16877492ea065cd26105830be12c72b06860ac5fc32ce7929d012588783/ProDy-1.10.2.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 470kB/s 
No files/directories in /tmp/pip-build-STCcBh/ProDy/pip-egg-info (from PKG-INFO)
```

3. Inside pipenv:
```
~/Source/pipenv_test via pipenv_test-UX5Ng_Zk 
➜ pip install -U ProDy 
Collecting ProDy
  Using cached https://files.pythonhosted.org/packages/40/52/f16877492ea065cd26105830be12c72b06860ac5fc32ce7929d012588783/ProDy-1.10.2.tar.gz
No files/directories in /tmp/pip-install-lfagrp_o/ProDy/pip-egg-info (from PKG-INFO)
```

Since I can't install prody in a virtual environment and/or from a dependency list file, it makes CI and usage in a Docker image complicated.

**Comment by SHZ66** [comment]
The new release is [out](https://pypi.org/project/ProDy/#description), and this problem should be fixed. Please confirm and I will close this issue for now.

**Comment by nffaruk** [comment]
Hello, I'm still experiencing this issue for ProDy 1.10.7 when trying to install to a conda environment (Python 3.6.5, pip 10.0.1).
