### ISSUE TITLE
Installing ProDy on Python3.7.3 from HomeBrew fails

### ISSUE THREAD

**Issue by aiotter** [prody/ProDy#864]
environment: python3.7.3 (installed via HomeBrew)

I tried to install ProDy and failed with the error below:
```bash
> pip install prody
...
  ERROR: Failed building wheel for prody
  Running setup.py clean for prody
Failed to build prody
ERROR: Could not build wheels for prody which use PEP 517 and cannot be installed directly
```
```bash
> python setup.py build
...
tbtools.c -o build/temp.macosx-10.13-x86_64-3.7/prody/dynamics/rtbtools.o
error: $MACOSX_DEPLOYMENT_TARGET mismatch: now "10.9" but "10.13" during configure
```

Deleting the L120 on setup.py solved the problem.
https://github.com/prody/ProDy/blob/24924940e286e82b28c87313bf5b210e133caaf1/setup.py#L120

This may be because I used the python3.7.3 from HomeBrew, in which $MACOSX_DEPLOYMENT_TARGET is set to 10.13.
```python
Python 3.7.3 (default, Mar 27 2019, 09:23:39)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var('MACOSX_DEPLOYMENT_TARGET')
'10.13'
```

**Comment by aiotter** [comment]
Oh, I forgot to tell you that after installing ProDy and when importing it, it said that it lacked pyparsing, so I had to install it. Now it works well.

**Comment by SHZ66** [comment]
Thank you for reporting it. I added this line earlier to resolve a C++ library dependency issue on clang  g++. I will look into this.

**Comment by jamesmkrieger** [comment]
This should be working now. We are running some final tests and will make a new release that resolves this issue soon. In the meantime, please could you try to install ProDy from the github version and let us know if it works for your computer.

Thanks

**Comment by brianjimenez** [comment]
`pip install prody` is still failing on macOS (10.13 for me). Is there any plan to make a new release soon to fix this problem? The `lightdock` package heavily depends on ProDy for the use of ANM in docking and its installation fails due to this problem. Thanks in advance for your help.

**Comment by jamesmkrieger** [comment]
Could you try cloning it from git and using `pip install -U .` instead?

**Comment by brianjimenez** [comment]
Installation went smooth @jamesmkrieger (Python 3.7, virtualenv):

```
(test) {bjimenez@abiko}->[~/workspaces/lightdocking/test/ProDy]: pip install -U .
Processing /Users/bjimenez/workspaces/lightdocking/test/ProDy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pyparsing (from ProDy==1.10.10)
  Using cached https://files.pythonhosted.org/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting biopython (from ProDy==1.10.10)
  Using cached https://files.pythonhosted.org/packages/36/3f/7947c2cd687e79f2904d2b8b0f8805cc344538f3849d7e187fc15db29b6e/biopython-1.74-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting numpy>=1.10 (from ProDy==1.10.10)
  Using cached https://files.pythonhosted.org/packages/b4/e8/5ececadd9cc220bb783b4ce6ffaa9266925d37ed41237bc23bc530ab4f3d/numpy-1.17.2-cp37-cp37m-macosx_10_6_intel.whl
Building wheels for collected packages: ProDy
  Building wheel for ProDy (PEP 517) ... done
  Created wheel for ProDy: filename=ProDy-1.10.10-cp37-cp37m-macosx_10_13_x86_64.whl size=1630737 sha256=a5149edfde8f0cc3ecd0b4387e8eb3beceb3122219856bbd14b7c96e64761440
  Stored in directory: /private/var/folders/80/l96xw1sx7nsblmr1svx29rph0000gn/T/pip-ephem-wheel-cache-_brzlnwd/wheels/b2/8f/21/cff61e0ae154799607387ff8409c7e943053d44f4d73e00532
Successfully built ProDy
Installing collected packages: pyparsing, numpy, biopython, ProDy
Successfully installed ProDy-1.10.10 biopython-1.74 numpy-1.17.2 pyparsing-2.4.2
```

**Comment by jamesmkrieger** [comment]
Great!

**Comment by SHZ66** [comment]
We just made a new release which includes a fix for this. Please feel free to try it out and see if it solves your problem. Thanks.
